# Generated by Django 5.0.9 on 2024-12-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0641_web_suggest_update_time_zone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realm",
            name="description",
            field=models.TextField(
                blank=True, default="The coolest place in the universe.", null=True
            ),
        ),
    ]
