# Generated by Django 5.0.9 on 2024-12-19 01:25

from django.db import migrations

DEFAULT_DESCRIPTION = 'The coolest place in the universe.'

def update_existing_org_descriptions(apps, schema_editor):
    Realm = apps.get_model('zerver', 'Realm')
    realms_to_update = Realm.objects.filter(description='')
    realms_to_update.update(description=DEFAULT_DESCRIPTION)

class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0642_alter_realm_description"),
    ]

    operations = [
        migrations.RunPython(update_existing_org_descriptions),
    ]
